#!/usr/bin/env python
"""Generate the declaration exhibits for docs/house-style.md."""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "ipakit/data/ipa.xml"
OUTPUT = ROOT / "docs/house-style-exhibits.md"


def _code(text: str) -> str:
    return f"`{text}`"


def _link(root: ET.Element, elem: ET.Element) -> str:
    href = elem.get("href")
    if not href:
        return "—"
    return f"[basis]({root.get('wiki', '')}{href})"


def _features(elem: ET.Element, *omit: str) -> str:
    hidden = {"name", "alias", "desc", "href", *omit}
    values = [
        f"{key}={value}" for key, value in elem.attrib.items() if key not in hidden
    ]
    return ", ".join(_code(value) for value in values) or "—"


def render() -> str:
    root = ET.parse(SOURCE).getroot()
    tie_marks = {
        elem.get("name", ""): elem
        for elem in root.findall("./suprasegmentals/suprasegmental")
        if elem.get("tie")
    }

    lines = [
        "<!-- Generated by scripts/house_style.py from ipakit/data/ipa.xml. -->",
        "# House-style declaration exhibits",
        "",
        "These tables are generated from `ipakit/data/ipa.xml`; edit the declarations and run `make house-style`.",
        "",
        "## Tie compounds",
        "",
        "| unit | tie reading | declaration | basis |",
        "| --- | --- | --- | --- |",
    ]
    tied = [
        elem
        for elem in root.findall("./phones/phone")
        if set(elem.get("name", "")) & set(tie_marks)
    ]
    for elem in tied:
        name = elem.get("name", "")
        mark = next(mark for mark in tie_marks if mark in name)
        tie = tie_marks[mark]
        lines.append(
            f"| {_code(name)} | {_code(tie.get('tie', ''))} | {tie.get('desc', '—')} | {_link(root, elem)} |"
        )

    lines += [
        "",
        "## Boundary vocabulary",
        "",
        "| mark | declared semantics | description | basis |",
        "| --- | --- | --- | --- |",
    ]
    boundary = [
        *root.findall("./separators/separator"),
        *(
            elem
            for elem in root.findall("./suprasegmentals/suprasegmental")
            if elem.get("level") is not None and elem.get("tie") is None
        ),
    ]
    for elem in boundary:
        lines.append(
            f"| {_code(elem.get('name', ''))} | {_features(elem)} | {elem.get('desc', '—')} | {_link(root, elem)} |"
        )

    lines += ["", "## Character classes", ""]
    for declaration in root.findall("./classes/class"):
        plural = declaration.get("name", "")
        singular = plural[:-1]
        members = [
            elem.get("name", "") for elem in root.findall(f"./{plural}/{singular}")
        ]
        lines += [
            f"### {plural}",
            "",
            f"{declaration.get('desc', '')} ([declared basis]({root.get('wiki', '')}{declaration.get('href', '')})).",
            "",
            " ".join(_code(member) for member in members),
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("generate", "check"))
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    rendered = render()
    if args.action == "generate":
        if args.write:
            OUTPUT.write_text(rendered, encoding="utf-8")
        else:
            sys.stdout.write(rendered)
        return 0
    shipped = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if shipped != rendered:
        print(
            "docs/house-style-exhibits.md has drifted; run make house-style",
            file=sys.stderr,
        )
        return 1
    print("OK: house-style exhibits match ipa.xml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
