#!/usr/bin/env python
"""Generate/check the Miller-Nicely perceptual-validation exhibits."""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "ipakit/data/attested/miller_nicely_1955.json"
OUTPUT = ROOT / "docs/perceptual-validation-exhibits.md"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import ipakit  # noqa: E402


def _ranks(values: list[float]) -> list[float]:
    """One-based ascending ranks with the average rank for ties."""
    order = sorted(range(len(values)), key=values.__getitem__)
    ranks = [0.0] * len(values)
    start = 0
    while start < len(order):
        end = start + 1
        while end < len(order) and values[order[end]] == values[order[start]]:
            end += 1
        rank = (start + 1 + end) / 2
        for index in order[start:end]:
            ranks[index] = rank
        start = end
    return ranks


def _correlation(left: list[float], right: list[float]) -> float:
    lmean = sum(left) / len(left)
    rmean = sum(right) / len(right)
    numerator = sum((a - lmean) * (b - rmean) for a, b in zip(left, right, strict=True))
    denominator = math.sqrt(
        sum((a - lmean) ** 2 for a in left) * sum((b - rmean) ** 2 for b in right)
    )
    return numerator / denominator


def measurements() -> dict[str, Any]:
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    phones = payload["inventory"]
    matrix = payload["matrix"]
    pairs = []
    for row in range(len(phones)):
        for column in range(row):
            left, right = phones[column], phones[row]
            pairs.append(
                {
                    "pair": f"{left}–{right}",
                    "left": left,
                    "right": right,
                    "confusion": matrix[row][column],
                    "distance": ipakit.segment_distance(left, right),
                }
            )
    confusion_ranks = _ranks([-pair["confusion"] for pair in pairs])
    distance_ranks = _ranks([pair["distance"] for pair in pairs])
    for pair, confusion_rank, distance_rank in zip(
        pairs, confusion_ranks, distance_ranks, strict=True
    ):
        pair["confusion_rank"] = confusion_rank
        pair["distance_rank"] = distance_rank
        pair["rank_gap"] = distance_rank - confusion_rank
    return {
        "rho": _correlation(confusion_ranks, distance_ranks),
        "pairs": pairs,
    }


def _terms(pair: dict[str, Any]) -> str:
    explanation = ipakit.explain_word_distance(pair["left"], pair["right"])[0]
    terms = []
    for term in explanation["terms"]:
        if term["cost"]:
            endpoints = ""
            if term["a"] is not None or term["b"] is not None:
                endpoints = f" ({term['a']} → {term['b']})"
            terms.append(f"{term['label']}{endpoints}={term['cost']:.4f}")
    return "; ".join(terms) or "all terms zero"


def _pair_table(title: str, pairs: list[dict[str, Any]], explain: bool) -> list[str]:
    lines = [f"## {title}", ""]
    if explain:
        lines += [
            "| pair | confusion | distance | nonzero `explain` terms |",
            "| --- | ---: | ---: | --- |",
        ]
        for pair in pairs:
            lines.append(
                f"| `{pair['pair']}` | {pair['confusion']:.3f} | "
                f"{pair['distance']:.4f} | {_terms(pair)} |"
            )
    else:
        lines += [
            "| pair | confusion | perceptual rank | distance | metric rank | rank gap |",
            "| --- | ---: | ---: | ---: | ---: | ---: |",
        ]
        for pair in pairs:
            lines.append(
                f"| `{pair['pair']}` | {pair['confusion']:.3f} | "
                f"{pair['confusion_rank']:.1f} | {pair['distance']:.4f} | "
                f"{pair['distance_rank']:.1f} | {pair['rank_gap']:+.1f} |"
            )
    return lines + [""]


def render() -> str:
    result = measurements()
    pairs = result["pairs"]
    most = sorted(pairs, key=lambda pair: (-pair["confusion"], pair["pair"]))[:5]
    least = sorted(pairs, key=lambda pair: (pair["confusion"], pair["pair"]))[:5]
    metric_far = sorted(pairs, key=lambda pair: (-pair["rank_gap"], pair["pair"]))
    perception_far = sorted(pairs, key=lambda pair: (pair["rank_gap"], pair["pair"]))
    far_cutoff = metric_far[4]["rank_gap"]
    near_cutoff = perception_far[4]["rank_gap"]
    metric_far = [pair for pair in metric_far if pair["rank_gap"] >= far_cutoff]
    perception_far = [
        pair for pair in perception_far if pair["rank_gap"] <= near_cutoff
    ]
    lines = [
        "<!-- Generated by scripts/perceptual_validation.py. -->",
        "# Miller–Nicely perceptual-validation exhibits",
        "",
        "The preregistered direction is **more confusable ⇒ nearer**. Perceptual "
        "rank 1 is most confusable; metric rank 1 is nearest. Average ranks handle "
        "ties. The diagonal is excluded by construction; all 120 unordered off-diagonal "
        "pairs are retained.",
        "",
        "```python",
        "miller_nicely_validation = {",
        '    "consonants": 16,',
        f'    "unordered pairs": {len(pairs)},',
        f'    "Spearman rho": {result["rho"]:.6f},',
        "}",
        "miller_nicely_validation",
        f"# {{'consonants': 16, 'unordered pairs': 120, 'Spearman rho': {result['rho']:.6f}}}",
        "```",
        "",
    ]
    lines += _pair_table("Five most-confused pairs", most, True)
    lines += _pair_table("Five least-confused pairs", least, True)
    lines += _pair_table(
        "Hard disagreements: metric farther than perception", metric_far, False
    )
    lines += _pair_table(
        "Hard disagreements: perception farther than metric", perception_far, False
    )
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("generate", "check"))
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    rendered = render()
    if args.action == "generate":
        if args.write:
            OUTPUT.write_text(rendered, encoding="utf-8")
        else:
            sys.stdout.write(rendered)
        return 0
    shipped = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if shipped != rendered:
        print("perceptual-validation exhibits have drifted", file=sys.stderr)
        return 1
    print("OK: perceptual-validation exhibits match data and metric")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
