#!/usr/bin/env python
"""Generate the current-state index from dated design assessments."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESIGN = ROOT / "docs" / "design"
OUTPUT = ROOT / "docs" / "state-of-the-work.md"

VERDICT = re.compile(r"^\*\*(Verdict(?: on [^:*]+|, first pass)?.*?)\*\*")
SUPERSEDED = re.compile(r"^\*\*(Superseded.*?)\*\*")
OPEN_WORDS = re.compile(
    r"^Verdict[^:]*:\s*(?:ADOPT|BUILD)|\bdefensible small adopt\b|"
    r"\bworth building\b",
    re.IGNORECASE,
)
REFUSED_WORDS = re.compile(
    r"\b(?:REFUSAL|REFUSE|REFUSED|DON'T ADMIT|DON'T BUILD|DO NOT BUILD|"
    r"DO NOT SHIP|SHIP NO|NOT DEFENSIBLE|CANNOT BE)\b",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class Finding:
    document: str
    heading: str
    anchor: str
    statement: str

    @property
    def link(self) -> str:
        return f"design/{self.document}#{self.anchor}"


def slug(text: str) -> str:
    """Return the GitHub-style anchor used by these ASCII headings."""
    text = re.sub(r"[^\w\s-]", "", text.lower(), flags=re.UNICODE)
    return re.sub(r"[\s-]+", "-", text).strip("-")


def findings() -> tuple[list[Finding], list[Finding]]:
    verdicts: list[Finding] = []
    superseded: list[Finding] = []
    for path in sorted(DESIGN.glob("*.md")):
        heading = path.stem
        anchor = slug(heading)
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                heading = line[2:]
                anchor = slug(heading)
            elif line.startswith("## "):
                heading = line[3:]
                anchor = slug(heading)
            elif line.startswith("### "):
                heading = line[4:]
                anchor = slug(heading)
            match = VERDICT.match(line)
            if match:
                verdicts.append(
                    Finding(path.name, heading, anchor, match.group(1).strip())
                )
            match = SUPERSEDED.match(line)
            if match:
                superseded.append(
                    Finding(path.name, heading, anchor, match.group(1).strip())
                )
    return verdicts, superseded


def row(item: Finding) -> str:
    label = f"{Path(item.document).stem} — {item.heading}"
    statement = re.sub(r"\]\(\.\./([^)]+)\)", r"](\1)", item.statement)
    statement = re.sub(
        r"\]\((?!https?://|#|design/)([^)]+)\)", r"](design/\1)", statement
    )
    return f"| [{label}]({item.link}) | {statement} |"


def section(title: str, items: list[Finding]) -> list[str]:
    lines = [
        f"## {title} ({len(items)})",
        "",
        "| design record | recorded state |",
        "| --- | --- |",
    ]
    lines.extend(row(item) for item in items)
    return lines + [""]


def render() -> str:
    verdicts, superseded = findings()
    opened = [item for item in verdicts if OPEN_WORDS.search(item.statement)]
    refused = [item for item in verdicts if REFUSED_WORDS.search(item.statement)]
    decided = [
        item
        for item in verdicts
        if not OPEN_WORDS.search(item.statement)
        and not REFUSED_WORDS.search(item.statement)
    ]
    settled = superseded + decided
    lines = [
        "<!-- Generated by scripts/state_of_work.py from docs/design/*.md. -->",
        "# State of the work",
        "",
        "This is the entry surface for the dated design records. It quotes their verdict lines and fixed-format superseded markers, then points to the argument; edit those records, not this page, and run `make state-of-work`.",
        "",
        "An open entry is a verdict that says to build or adopt. A refusal says so explicitly. Settled includes superseded findings and verdicts that record an answer without either instruction. A mixed verdict appears in both sections.",
        "",
    ]
    lines += section("Settled", settled)
    lines += section("Open", opened)
    lines += section("Refused", refused)
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("generate", "check"))
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    rendered = render()
    if args.action == "generate":
        if args.write:
            OUTPUT.write_text(rendered, encoding="utf-8")
        else:
            sys.stdout.write(rendered)
        return 0
    shipped = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if shipped != rendered:
        print(
            "docs/state-of-the-work.md has drifted; run make state-of-work",
            file=sys.stderr,
        )
        return 1
    print("OK: state of the work matches docs/design")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
