#!/usr/bin/env python
"""Generate and validate the IPA <-> X-SAMPA table (data/phonemaps/xsampa.xml).

The table is *derived*, not hand-maintained value-by-value:

    xsampa(symbol) = OVERRIDES[symbol]              if curated, else
                     ICU "IPA-XSampa"(symbol)       if ICU maps it, else
                     <skipped>                       (ICU passthrough of non-ASCII)

over an inventory drawn from ipakit's own phone/diacritic set (plus a few
structural X-SAMPA symbols, minus a few combining marks X-SAMPA folds elsewhere).

This keeps the table reproducible and the human judgement calls explicit:
  * OVERRIDES  - symbols ICU can't transliterate (tone bars, suprasegmentals,
                 a few rare phones). Each is a deliberate, documented choice.
  * EXTRAS     - X-SAMPA structural symbols not in the IPA inventory.
  * EXCLUDE    - inventory symbols intentionally kept out of the table.

Usage:
    python scripts/xsampa_table.py validate          # CI guard: shipped == derived
    python scripts/xsampa_table.py generate          # print derived table to stdout
    python scripts/xsampa_table.py generate --write   # overwrite xsampa.xml

Requires the dev dependency `icukit-pyicu` (bundled ICU + PyICU, `import icu`).
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import quoteattr

# Make the package importable when run from a source checkout.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ipakit.constants import PHONEMAPS_DIR, TIE_BAR  # noqa: E402
from ipakit.features import IPAFeatures  # noqa: E402

XSAMPA_FILE = PHONEMAPS_DIR / "xsampa.xml"

# IPA symbols ICU's "IPA-XSampa" transliterator does not handle (it passes them
# through unchanged) or maps differently from established X-SAMPA. Curated.
OVERRIDES: dict[str, str] = {
    "␣": "*",  # silence placeholder
    "‿": "-\\",  # linking (absence of a break)
    "ʱ": "_hh",  # breathy-voiced / murmured release
    "ᶣ": "_H_w",  # labial-palatal approximant release
    "ť": "t_>",  # ejective (legacy caron form)
    "ȡ": "d_j\\",  # curly-tail d (alveolo-palatal)
    "ȴ": "l_j\\",  # curly-tail l (alveolo-palatal)
    "ȶ": "t_j\\",  # curly-tail t (alveolo-palatal)
    "ʴ": "`",  # rhoticity
    "˥": "_T",  # extra-high tone bar
    "˦": "_H",  # high tone bar
    "˧": "_M",  # mid tone bar
    "˨": "_L",  # low tone bar
    "˩": "_B",  # extra-low tone bar
    "ꜛ": "^",  # upstep
    "ꜜ": "!",  # downstep
    "‖": "||",  # major (intonation) group
}

# X-SAMPA structural symbols that are not phones/diacritics in the inventory.
EXTRAS: set[str] = {"#", ".", TIE_BAR}

# Inventory symbols deliberately excluded from the table. These combining marks
# are folded into the tone-bar / rhotic entries above, so listing them too would
# create redundant (and ambiguous) X-SAMPA encodings.
EXCLUDE: set[str] = {"˞", "̀", "́", "̄", "̞"}


def _icu_forward():  # type: ignore[no-untyped-def]
    """Return the ICU IPA->X-SAMPA transliterator, or exit with guidance."""
    try:
        import icu
    except ImportError:
        sys.exit(
            "icukit-pyicu is required (dev dependency). Install with:\n"
            '    pip install -e ".[dev]"'
        )
    return icu.Transliterator.createInstance("IPA-XSampa")


def canonical_pairs() -> dict[str, str]:
    """Compute the derived IPA -> X-SAMPA table."""
    fwd = _icu_forward()
    ipa = IPAFeatures()
    inventory = (
        {s for s in (set(ipa.phones) | set(ipa.diacritics)) if TIE_BAR not in s}
        | EXTRAS
    ) - EXCLUDE

    table: dict[str, str] = {}
    for sym in inventory:
        if sym in OVERRIDES:
            table[sym] = OVERRIDES[sym]
            continue
        x = fwd.transliterate(sym)
        if x == sym and not sym.isascii():
            continue  # ICU has no X-SAMPA for this symbol; skip
        table[sym] = x
    return table


def shipped_pairs() -> dict[str, str]:
    """Load the IPA -> X-SAMPA pairs currently shipped in xsampa.xml."""
    root = ET.parse(XSAMPA_FILE).getroot()
    pairs: dict[str, str] = {}
    for m in root.findall("map"):
        ip, xs = m.get("ipa"), m.get("xsampa")
        if ip is not None and xs is not None:
            pairs[ip] = xs
    return pairs


def render(table: dict[str, str]) -> str:
    """Render a table as a phonemap XML document (sorted by IPA codepoint)."""
    lines = [
        "<?xml version='1.0' encoding='utf-8'?>",
        '<phonemap description="IPA to X-SAMPA">',
        "    <!-- Generated by scripts/xsampa_table.py (ICU + curated overrides). -->",
    ]
    for ip in sorted(table):
        lines.append(f"    <map ipa={quoteattr(ip)} xsampa={quoteattr(table[ip])}/>")
    lines.append("</phonemap>")
    return "\n".join(lines) + "\n"


def cmd_validate(_: argparse.Namespace) -> int:
    derived = canonical_pairs()
    shipped = shipped_pairs()

    missing = {k: derived[k] for k in derived.keys() - shipped.keys()}
    extra = {k: shipped[k] for k in shipped.keys() - derived.keys()}
    mismatch = {
        k: (shipped[k], derived[k])
        for k in derived.keys() & shipped.keys()
        if shipped[k] != derived[k]
    }

    if not (missing or extra or mismatch):
        print(f"OK: shipped xsampa.xml matches derived table ({len(shipped)} entries).")
        return 0

    print("DRIFT between shipped xsampa.xml and the derived (ICU + overrides) table:")
    for k, v in sorted(missing.items()):
        print(f"  missing (derived has, shipped lacks): {k!r} -> {v!r}")
    for k, v in sorted(extra.items()):
        print(f"  extra (shipped has, derived lacks):    {k!r} -> {v!r}")
    for k, (s, d) in sorted(mismatch.items()):
        print(f"  mismatch {k!r}: shipped={s!r}  derived={d!r}")
    return 1


def cmd_generate(args: argparse.Namespace) -> int:
    table = canonical_pairs()
    text = render(table)
    if args.write:
        XSAMPA_FILE.write_text(text, encoding="utf-8")
        print(f"Wrote {len(table)} entries to {XSAMPA_FILE}")
    else:
        sys.stdout.write(text)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_val = sub.add_parser("validate", help="check shipped table matches derived")
    p_val.set_defaults(func=cmd_validate)

    p_gen = sub.add_parser("generate", help="emit the derived table")
    p_gen.add_argument(
        "--write",
        action="store_true",
        help="overwrite data/phonemaps/xsampa.xml (loses hand grouping/comments)",
    )
    p_gen.set_defaults(func=cmd_generate)

    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
