#!/usr/bin/env python3
"""Generate the shipped ZIPA recognizer vocabulary declaration.

The input is the MIT-licensed SentencePiece vocabulary at the exact ZIPA
revision below.  The upstream file is a development input and does not ship.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import quoteattr

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from ipakit.form import Form  # noqa: E402

REVISION = "d6f7cbc74b29ab7cb0248a5cf2d93f116d79721d"
PIN = f"lingjzhu/zipa@{REVISION}"
UPSTREAM = "ZIPA"
UPSTREAM_URL = (
    "https://github.com/lingjzhu/zipa/blob/"
    f"{REVISION}/ipa_simplified/unigram_127.vocab"
)
ARTIFACT = "ipa_simplified/unigram_127.vocab"
LICENSE = "MIT"
KIND = "recognizer-phone-vocabulary"
SHA256 = "fc3efb3780b98ed1afd096699afb51eb53ccba10c59b9ff38605747d22f82ae8"
OUTPUT = ROOT / "ipakit" / "data" / "bridges" / "zipa" / "zipa.xml"

NON_PHONE_MARKERS = ("<blk>", "<sos/eos>", "<unk>")
WORD_BOUNDARY = "▁"
MARKS = frozenset(
    {"ʼ", "̥", "ʰ", "̩", "˞", "ʷ", "ʲ", "ˠ", "ˤ", "̴", "̪", "̺", "̃", "̚", "ː"}
)
EXPECTED_BASES = 108

TIE_DROP = "tie bars absent from the ZIPA vocabulary"
STRESS_DROP = "stress absent from the ZIPA vocabulary"
TONE_DROP = "tone absent from the ZIPA vocabulary"
EXTRA_MARK_DROP = "diacritics beyond the first absent from the ZIPA vocabulary"
UNSUPPORTED_MARK_DROP = "diacritics ̯ ̤ ̆ ̈ ˑ absent from the ZIPA vocabulary"
LOSSES = (TIE_DROP, STRESS_DROP, TONE_DROP, EXTRA_MARK_DROP, UNSUPPORTED_MARK_DROP)


def tokens(source: Path) -> tuple[str, ...]:
    """Validate and return the pinned vocabulary tokens in source order."""
    payload = source.read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if digest != SHA256:
        raise ValueError(
            f"ZIPA vocabulary has sha256:{digest}; required sha256:{SHA256}"
        )
    values = []
    for line_number, raw in enumerate(payload.decode("utf-8").splitlines(), 1):
        fields = raw.split("\t")
        if len(fields) != 2 or not fields[0]:
            raise ValueError(f"ZIPA vocabulary line {line_number} is malformed")
        values.append(fields[0])
    if len(values) != len(set(values)):
        raise ValueError("ZIPA vocabulary tokens are not unique")
    expected = set(NON_PHONE_MARKERS) | {WORD_BOUNDARY}
    if not expected <= set(values):
        raise ValueError(
            f"ZIPA vocabulary is missing special tokens {sorted(expected - set(values))!r}"
        )
    bases = [
        token
        for token in values
        if token not in MARKS
        and token not in NON_PHONE_MARKERS
        and token != WORD_BOUNDARY
    ]
    if len(values) != 127 or len(bases) != EXPECTED_BASES or len(MARKS) != 15:
        raise ValueError(
            "ZIPA vocabulary census differs from 108 bases, 15 marks, "
            "one boundary, and three non-phone markers"
        )
    for token in bases:
        spelling = "ɡ" if token == "g" else token
        try:
            parsed = Form.parse(spelling, strict=True)
        except ValueError as error:
            raise ValueError(
                f"ZIPA token {token!r} has no ruled house spelling"
            ) from error
        if len(parsed.units) != 1:
            raise ValueError(f"ZIPA token {token!r} is not one house unit")
    for mark in MARKS:
        try:
            Form.parse("a" + mark, strict=True)
        except ValueError as error:
            raise ValueError(
                f"ZIPA mark {mark!r} is not a house trailing mark"
            ) from error
    return tuple(values)


def render(values: tuple[str, ...]) -> str:
    """Render one deterministic ipakit-owned bridge declaration."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- Generated by scripts/zipa_vocabulary.py from {PIN}; sha256:{SHA256}. -->",
        (
            f"<vocabulary name={quoteattr('zipa')} version={quoteattr(PIN)} "
            f"upstream={quoteattr(UPSTREAM)} upstream-url={quoteattr(UPSTREAM_URL)} "
            f"artifact={quoteattr(ARTIFACT)} license={quoteattr(LICENSE)} "
            f"kind={quoteattr(KIND)} tier={quoteattr('zipa')} "
            'source-style="segmented" separator=" ">'
        ),
        "  <round-trip>",
        '    <external-to-house fidelity="lossless" />',
        '    <house-to-external fidelity="lossy-with-report">',
        *(f"      <drop name={quoteattr(loss)} />" for loss in LOSSES),
        "    </house-to-external>",
        "  </round-trip>",
        f"  <mapper tie-drop={quoteattr(TIE_DROP)} />",
    ]
    for marker in NON_PHONE_MARKERS:
        lines.append(
            f"  <refusal spelling={quoteattr(marker)} "
            'reason="ZIPA control marker does not denote a phone" />'
        )
    for token in values:
        if token in NON_PHONE_MARKERS:
            continue
        if token == WORD_BOUNDARY:
            lines.append(
                f"  <atom spelling={quoteattr('#')} output={quoteattr(token)} "
                'notes="word boundary" />'
            )
        elif token in MARKS:
            lines.append(
                f"  <atom spelling={quoteattr(token)} kind={quoteattr('mark')} />"
            )
        elif token == "g":
            lines.append(
                f"  <atom spelling={quoteattr('ɡ')} output={quoteattr(token)} />"
            )
        else:
            lines.append(f"  <atom spelling={quoteattr(token)} />")
    lines.extend(("</vocabulary>", ""))
    return "\n".join(lines)


def validate_declaration(payload: str, values: tuple[str, ...]) -> None:
    """Require exactly one declaration route for every pinned token."""
    root = ET.fromstring(payload)
    declared = [
        item.attrib.get("output", item.attrib["spelling"])
        for item in root.findall("atom")
    ]
    declared.extend(item.attrib["spelling"] for item in root.findall("refusal"))
    missing = sorted(set(values) - set(declared))
    extra = sorted(set(declared) - set(values))
    if missing or extra or len(declared) != len(values):
        raise ValueError(
            f"ZIPA declaration token mismatch: missing {missing!r}, extra {extra!r}"
        )


def main(argv: list[str] | None = None) -> int:
    """Generate or check the shipped declaration against a pinned source file."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("generate", "check"))
    parser.add_argument("--source", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        values = tokens(args.source)
        rendered = render(values)
        validate_declaration(rendered, values)
        if args.action == "generate":
            OUTPUT.parent.mkdir(parents=True, exist_ok=True)
            OUTPUT.write_text(rendered, encoding="utf-8")
        elif not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                "zipa-vocabulary: generated artifact differs; run "
                "scripts/zipa_vocabulary.py generate --source PATH",
                file=sys.stderr,
            )
            return 1
    except (OSError, UnicodeError, ValueError) as error:
        print(f"zipa-vocabulary: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
